version: "3.9"
services:

  # ------------------------------
  # MongoDB Datastore
  # ------------------------------
  mongodb:
    image: mongo:6
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo_data:/data/db
    command : ["/bin/sh", "-c", "mongod --replSet rs0 --port 27017 --bind_ip 0.0.0.0 --dbpath /data/db/"]

  mongo-init: # Once finished, Mongo is assumed to be ready.
    image: mongo:6
    depends_on:
      - mongodb
    volumes:
      - ./mongo-init.sh:/scripts/mongo-init.sh
    env_file:
    - users.env
    command: sh -c "/scripts/mongo-init.sh"


   # Vector Search Service
   # ------------------------------
  vector-search:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: vector-search
    ports:
      - "8000:8000"
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/user_db'
      SUPERDUPERDB_CLUSTER_VECTOR_SEARCH: 'http://localhost:8000'
    command:
      - /bin/sh
      - -c
      - |
        python -m superduperdb vector-search

    healthcheck:
      test: curl http://localhost:8000/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 10
      start_period: 60s

  vector-search-init: # Once finished, Vector Search is assumed to be ready.
    image: busybox
    depends_on:
      vector-search:
        condition: service_healthy


   # Change Data Capture Service
   # ------------------------------
  cdc:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: cdc
    ports:
      - "8001:8001"
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/user_db'
      SUPERDUPERDB_CLUSTER_CDC: 'http://localhost:8001'
    command:
      - /bin/sh
      - -c
      - |
        python -m superduperdb cdc

    healthcheck:
      test: curl http://localhost:8001/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 10
      start_period: 60s

  cdc-init: # Once finished, CDC is assumed to be ready.
    image: busybox
    depends_on:
      cdc:
        condition: service_healthy


  # Dask Parallel Computation
  # ------------------------------
  dask-scheduler:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: scheduler
    ports:
      - "8786:8786" # Peer communication
      - "8787:8787" # HTTP Dashboard
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/user_db'
    command:
      - /bin/sh
      - -c
      - |
        PYTHONPATH=./:. dask scheduler --preload deploy/testenv/preload.py

  dask-worker:
    depends_on:
      -   dask-scheduler
    image: superduperdb/sandbox
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/user_db'
    command:
      - /bin/sh
      - -c
      - |
        PYTHONPATH=./:. dask worker "tcp://scheduler:8786" --preload deploy/testenv/preload.py
    deploy:
      replicas: 1

  #  Demo SuperDuperDB Notebooks
  #  ------------------------------
  demo-notebooks:
    image: superduperdb/sandbox
    hostname: demo
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      vector-search-init:
        condition: service_completed_successfully
      cdc-init:
        condition: service_completed_successfully
      dask-scheduler:
        condition: service_started
      dask-worker:
        condition: service_started
    ports:
      - "8888:8888" # HTTP Notebooks
    volumes:
        - ../../:/home/superduper/superduperdb # mount the project path
    command:
      - /bin/sh
      - -c
      - |
        jupyter lab --port=8888 --no-browser --ip=0.0.0.0
