version: "3.9"


# set env variable COMPOSE_PROJECT_NAME and
# label com.docker.compose.project
name: testenv


services:

  # ------------------------------
  # MongoDB Datastore
  # ------------------------------
  mongodb:
    image: mongo:6
    hostname: mongodb
    volumes:
      - ${SUPERDUPERDB_DATA_DIR:-.test_data}:/data/db
    ports:
      - "27017:27017"
    command : ["/bin/sh", "-c", "mongod --replSet rs0 --port 27017 --bind_ip 0.0.0.0 --dbpath /data/db/"]

  mongo-init: # Once finished, Mongo is assumed to be ready.
    image: mongo:6
    depends_on:
      - mongodb
    volumes:
      - ./mongo-init.sh:/scripts/mongo-init.sh
    env_file:
    - users.env
    command: sh -c "/scripts/mongo-init.sh"


   # Vector Search Service
   # ------------------------------
  vector-search:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: vector-search
    ports:
      - "8000:8000"
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/test_db'
      SUPERDUPERDB_CLUSTER_VECTOR_SEARCH: 'http://localhost:8000'
    command:
      - /bin/sh
      - -c
      - |
        python -m superduperdb vector-search

    healthcheck:
      test: curl http://localhost:8000/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 10
      start_period: 60s

  vector-search-init: # Once finished, Vector Search is assumed to be ready.
    image: busybox
    depends_on:
      vector-search:
        condition: service_healthy


   # Change Data Capture Service
   # ------------------------------
  cdc:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: cdc
    ports:
      - "8001:8001"
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/test_db'
      SUPERDUPERDB_CLUSTER_CDC: 'http://localhost:8001'
    command:
      - /bin/sh
      - -c
      - |
        python -m superduperdb cdc

    healthcheck:
      test: curl http://localhost:8001/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 10
      start_period: 60s

  cdc-init: # Once finished, CDC is assumed to be ready.
    image: busybox
    depends_on:
      cdc:
        condition: service_healthy


  # Dask Parallel Computation
  # ------------------------------
  dask-scheduler:
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    image: superduperdb/sandbox
    hostname: scheduler
    ports:
      - "8786:8786" # Peer communication
      - "8787:8787" # HTTP Dashboard
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/test_db'
    command:
      - /bin/sh
      - -c
      - |
        PYTHONPATH=./:. dask scheduler --preload deploy/testenv/preload.py

  dask-worker:
    depends_on:
      -   dask-scheduler
    image: superduperdb/sandbox
    volumes:
      - ../../:/home/superduper/superduperdb # mount the project path
    environment:
      SUPERDUPERDB_DATA_BACKEND: 'mongodb://superduper:superduper@mongodb:27017/test_db'
    command:
      - /bin/sh
      - -c
      - |
        PYTHONPATH=./:. dask worker "tcp://scheduler:8786" --preload deploy/testenv/preload.py
    deploy:
      replicas: 1


  #  Real-time Dashboards
  #  ------------------------------
  grafana:
    depends_on:
      - loki
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
    volumes:
        - ./configs/grafana:/app.cfg


  #  Logging with Loki
  #  ------------------------------
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki:/etc/loki
    command: -config.file=/etc/loki/loki-local-config.yaml

  promtail:
    depends_on:
        - loki
    image: grafana/promtail:2.9.0
    volumes:
        # Configuration
        - ./configs/promtail:/etc/promtail
        # Read container labels and logs
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml


  #  Monitoring with Prometheus
  #  ------------------------------
  prometheus:
    image: prom/prometheus:v2.7.1
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus:/app.cfg
    command: >-
      --config.file=/app.cfg/prometheus.yml
      --storage.tsdb.path=/prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro


  #  Demo SuperDuperDB Notebooks
  #  ------------------------------
  demo-notebooks:
    image: superduperdb/sandbox
    hostname: demo
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      vector-search-init:
        condition: service_completed_successfully
      cdc-init:
        condition: service_completed_successfully
      dask-scheduler:
        condition: service_started
      dask-worker:
        condition: service_started
    ports:
      - "8888:8888" # HTTP Notebooks
    volumes:
        - ../../:/home/superduper/superduperdb # mount the project path
    command:
      - /bin/sh
      - -c
      - |
        jupyter lab --port=8888 --no-browser --ip=0.0.0.0
