
artifact_store: filesystem:///tmp/artifacts
bytes_encoding: Bytes
cluster:
  rest:
    uri: http://localhost:8002
    config: deploy/rest/config.yaml
data_backend: mongomock://test
downloads:
  folder: null
  headers:
    User-Agent: me
  n_workers: 0
  timeout: null
fold_probability: 0.05
lance_home: .superduperdb/vector_indices
log_level: INFO
logging_type: SYSTEM
metadata_store: null
retries:
  stop_after_attempt: 2
  wait_max: 10.0
  wait_min: 4.0
  wait_multiplier: 1.0
