version: "3.9"
services:

  # Microsoft SQL Server
  # ------------------------------
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Superduper#1"