artifact_store: null
bytes_encoding: Bytes
cluster:
  cdc:
    uri: null
  compute:
    uri: null
  vector_search:
    type: native 
data_backend: mongodb+srv://<your-mongodb-atlas-ip>:27017/test_db
downloads:
  folder: null
  headers:
    User-Agent: me
  n_workers: 0
  timeout: null
fold_probability: 0.05
lance_home: .superduper/vector_indices
log_level: INFO
logging_type: SYSTEM
metadata_store: null
retries:
  stop_after_attempt: 2
  wait_max: 10.0
  wait_min: 4.0
  wait_multiplier: 1.0
