data_backend: mongodb://superduper:superduper@mongodb:27017/test_db

cluster:
  cdc:
    uri: http://localhost:8001
  compute:
    uri: null
  vector_search:
    uri: http://localhost:8000
  rest:
    uri: http://localhost:8002
