version: "3.9"
services:

  # MySQL
  # ------------------------------
  mysql:
    image: mysql:8.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: superduper
      MYSQL_PASSWORD: superduper
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 'root'