apiVersion: 1

datasources:
- name: loki
  access: proxy
  type: loki
  url: http://loki:3100
  isDefault: true
  database: ''
  user: ''
  password: ''
  basicAuth: false
  id: 1
  orgId: 1
  readOnly: false
  jsonData:
    keepCookies: []
  typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
- name: prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: false
  orgId: 1
  editable: false
  jsonData:
    timeInterval: 10s
