version: "3.9"
services:
  # Run MongoDB
  # ------------------------------
  mongodb:
    image: mongo:7
    environment:
      # create root account in `admin` database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

      # create superduper account
      SDDB_USER: ${SDDB_USER}
      SDDB_PASS: ${SDDB_PASS}
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro


  # Run SuperDuperDB with Jupyter
  # ------------------------------
  superduperdb:
    depends_on:
      - mongodb
    image: superduperdb/superduperdb:0.0.13
    ports:
      - "8888:8888"
    command: ["jupyter", "lab", "--ip='*'", "--LabApp.token=''"]
    environment:
        MONGODB_URI: "mongodb://${SDDB_USER}:${SDDB_PASS}@mongodb"