name: Publish Doc Changes
on:
  push:
    branches:
      - main
    paths:  # run this action only when the docs folder is changed
      - 'docs/hr/content/**'
      - 'docs/hr/blog/**'

# allow the action to write to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

        # required for docs/hr/build to be available
      - name: Install node
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
          path: |
            ${{ env.pythonLocation }}
          key: 3.10-ubuntu-latest-${{ hashFiles('.github/ci-pinned-requirements/docs.txt') }}

      - name: Build docs and use-cases
        # build is available in docs/hr/build
        run: |
          make hr-docs

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r .github/ci-pinned-requirements/docs.txt
    
      - name: Build inline api docs
        # build is available in docs/hr/build/apidocs
        run: |
          make api-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/hr/build
          cname: docs.superduperdb.com
          enable_jekyll: true
