name: Build Doc Website
on:
  push:
    branches:
      - main
    paths:  # run this action only when the docs folder is changed
      - 'docs/content/**'
      - 'docs/*.js'
  workflow_dispatch:  # allows triggering a GitHub action manually - see 'Actions' tab


# allow the action to write to the gh-pages branch
permissions:
  contents: write

jobs:
  #---------------------------------------------------
  # Release Docs
  #---------------------------------------------------
  build-and-release-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

        # required for docs/hr/build to be available
      - name: Install node
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
          key: ubuntu-latest_python-3.11_${{ hashFiles('pyproject.toml', '*/pyproject.toml') }}

      - name: Install DevKit (docs, testing, etc)
        run: |
          make install_devkit

      - name: Build docs
        run: |
          # Build HR and API docs
          make gen_docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          cname: docs.superduperdb.com
