name: New documentation
on:
  push:
    branches:
      - main
    paths:  # only run this action when the newdocs folder is changed
      - 'docs/content/**'

# allow the action to write to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

        # required for 
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install nodejs npm

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
          path: |
            ${{ env.pythonLocation }}
          key: 3.10-ubuntu-latest-${{ hashFiles('.github/ci-pinned-requirements/docs.txt') }}

      - name: Build docs and use-cases
        run: |
          cd docs
          npm i
          npm run build
          cd ..

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r .github/ci-pinned-requirements/docs.txt
    
      - name: Build api docs
        # doc build is available in .cache/docs
        run: |
          python -m superduperdb docs

      - name: Copy api docs to build directory
        run: |
          cp -r .cache/apidocs docs/build/apidocs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          cname: docs.superduperdb.com
          enable_jekyll: true
