name: Release nightly build in DockerHub
on:
  workflow_dispatch:


jobs:
  #---------------------------------------------------
  # Publish Nightly Sandbox in DockerHub
  #---------------------------------------------------
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Sandbox Image
        run: |
          make testenv_image

      - name: Release Sandbox Image
        run: |
          @echo "===> release superduperdb/superduperdb:latest"
          docker push superduperdb/sandbox:latest

          tag=$(date +'%Y%m%d')
          echo "===> release superduperdb/sandbox:${tag}"
          docker tag superduperdb/sandbox:latest superduperdb/sandbox:${tag} 
          docker push superduperdb/sandbox:${tag}
