name: test latest dependency versions and external web links

on:
  schedule:
    # Triggers the workflow every day at 0130 UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
    # Checks imports using latest versions of dependencies for the core package.
    check-imports-latest-core-deps:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
              python-version: ["3.8"]
        defaults:
            run:
              shell: bash
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              id: setup-python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install latest versions of core dependencies.
              run: |
                python3 -m pip install --upgrade pip-tools
                python3 -m pip install .

            # smoke-tests that check imports
            - name: Check imports
              # these modules cover most of the imports for the core package
              # Note: if these modules are renamed, please update this list
              run: |
                python -m superduperdb.db.base.db
                python -m superduperdb.db.base.backends
                python -m superduperdb.container.model 

    # Run tests using latest versions of dependencies for the dev environment.
    test-latest-dev-deps:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              os: [ "ubuntu-latest" ]  # TODO: add "windows-latest", "macos-latest" when Docker removed
              python-version: ["3.8"]
        defaults:
            run:
              shell: bash
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              id: setup-python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install latest versions of developer dependencies
              run: |
                python3 -m pip install --upgrade pip-tools
                python3 -m pip install .[dev]

            - name: Run tests
              run: make test

    markdown-link-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
